name: CORDEX
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.5.5
  - anyio=2.1.0
  - argon2-cffi=20.1.0
  - astropy=4.1
  - async_generator=1.10
  - attrs=20.3.0
  - awscli=1.16.210
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - basemap=1.2.0
  - basemap-data=1.3.2
  - basemap-data-hires=1.3.2
  - beautifulsoup4=4.8.0
  - blas=2.14
  - bleach=3.3.0
  - blinker=1.4
  - boost-cpp=1.70.0
  - botocore=1.12.200
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2023.7.22
  - cartopy=0.16.0
  - certifi=2020.12.5
  - certipy=0.1.3
  - cffi=1.14.5
  - cftime=1.0.3.4
  - cgal-cpp=5.0.1
  - chardet=3.0.4
  - colorama=0.3.9
  - configobj=5.0.6
  - contextvars=2.4
  - cryptography=3.4.4
  - curl=7.71.1
  - cycler=0.10.0
  - dataclasses=0.7
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docutils=0.14
  - eigen=3.3.9
  - entrypoints=0.3
  - expat=2.4.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - future=0.18.2
  - geos=3.6.2
  - glib=2.69.0
  - gmp=6.2.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gudhi=3.1.1
  - h5py=2.9.0
  - hdf4=4.2.15
  - hdf5=1.10.4
  - healpy=1.12.9
  - icu=58.2
  - idna=2.10
  - immutables=0.15
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - iniconfig=1.1.1
  - ipykernel=5.5.0
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jbig=2.1
  - jedi=0.17.2
  - jinja2=2.10.1
  - jmespath=0.10.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-offlinenotebook=0.2.1
  - jupyter-resource-usage=0.5.1
  - jupyter_client=6.1.11
  - jupyter_core=4.7.1
  - jupyter_server=1.4.0
  - jupyter_telemetry=0.1.0
  - jupyterhub-base=1.2.2
  - jupyterhub-singleuser=1.2.2
  - jupyterlab=3.0.7
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.3.0
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnetcdf=4.6.2
  - libnghttp2=1.43.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=1.0.3
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - mako=1.1.4
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - more-itertools=8.8.0
  - mpfr=4.1.0
  - nbclassic=0.2.6
  - nbclient=0.5.2
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - netcdf4=1.4.2
  - netcdftime=1.0.0a2
  - notebook=6.2.0
  - nteract_on_jupyter=2.1.3
  - numpy=1.17.0
  - numpy-base=1.17.0
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1j
  - owslib=0.19.2
  - packaging=20.9
  - pamela=1.0.0
  - pandas=0.24.2
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - parso=0.7.1
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.1.1
  - pluggy=0.13.1
  - podaacpy=2.2.1
  - pot=0.7.0
  - proj4=5.0.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.16
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - pyasn1=0.4.8
  - pycparser=2.20
  - pycurl=7.43.0.6
  - pyepsg=0.4.0
  - pygments=2.8.0
  - pyjwt=2.0.1
  - pykdtree=1.3.4
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=1.9.5.1
  - pyqt=5.9.2
  - pyresample=1.12.3
  - pyrsistent=0.17.3
  - pyshp=2.1.3
  - pysocks=1.7.1
  - pytest=6.2.4
  - pytest-runner=5.3.1
  - python=3.6.13
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python-json-logger=2.0.1
  - python_abi=3.6
  - pytz=2021.1
  - pyyaml=5.1
  - pyzmq=22.0.3
  - qt=5.9.7
  - readline=8.0
  - requests=2.25.1
  - rsa=3.4.2
  - ruamel.yaml=0.16.12
  - ruamel.yaml.clib=0.2.2
  - s3transfer=0.2.1
  - scipy=1.3.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.15.0
  - sniffio=1.2.0
  - soupsieve=2.2.1
  - sqlalchemy=1.3.23
  - sqlite=3.34.0
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.32.1
  - traitlets=4.3.3
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xarray=0.12.1
  - xz=5.2.5
  - yaml=0.1.7
  - zeromq=4.3.4
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.5.0
