name: rcmes
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - jupyter-rsession-proxy
  - jupyter-shiny-proxy
  - numpy
  - pot
  - awscli
  - basemap
  - beautifulsoup4
  - botocore
  - cartopy
  - cftime
  - chardet
  - gudhi
  - h5py
  - healpy
  - jinja2
  - matplotlib=3.2
  - netcdf4
  - pandas
  - pillow
  - pip
  - podaacpy
  - pyresample
  - scipy
  - tqdm
  - xarray
  - openvisus
  - bokeh
